ARG BASE_IMAGE=node:14
FROM ${BASE_IMAGE}
LABEL maintainer "kokororin <i@kotori.love>"

ADD https://raw.githubusercontent.com/kokororin/dotfiles/master/.npmrc /root/

RUN npm install -g npm@latest \
    npm install -g cnpm@latest \
    npm install -g pnpm@latest
